# Generated by Django 2.1.1 on 2018-10-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('time_of_last', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FBUserSound',
            fields=[
                ('sound_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('remote_location', models.TextField(default='Missing')),
                ('is_uploaded', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=256)),
            ],
        ),
    ]
