# Generated by Django 2.0.9 on 2019-03-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSound',
            fields=[
                ('sound_id', models.AutoField(primary_key=True, serialize=False)),
                ('remote_location', models.TextField(default='Missing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.FBUser')),
            ],
        ),
    ]
