# Generated by Django 3.0.2 on 2020-05-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersound',
            old_name='user',
            new_name='user_id',
        ),
    ]
