# Generated by Django 3.0.2 on 2020-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_content',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Shoal', 'Shoal'), ('Dusk', 'Dusk'), ('Hall', 'Hall'), ('Animals', 'Animals'), ('Urban', 'Urban')], max_length=15),
        ),
        migrations.AlterField(
            model_name='usersound',
            name='image_file',
            field=models.ImageField(default='default.png', null=True, upload_to='sound_images'),
        ),
    ]
