# Generated by Django 3.0.2 on 2020-05-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200512_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersound',
            old_name='user_id',
            new_name='user',
        ),
    ]
