# Generated by Django 3.0.2 on 2020-05-16 03:53

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200512_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='your/upload/dir'),
        ),
    ]
